_wandb:
    value:
        cli_version: 0.23.1
        e:
            0c67cjn38jrcsdu6y4c5zx2v3yn5e58r:
                codePath: train.py
                codePathLocal: train.py
                email: kjink9921@gmail.com
                executable: /Users/daniel/team_project/myenv/bin/python
                git:
                    commit: fa6f7f57ce240e3b542796ceb623af28d5b69d43
                    remote: https://github.com/jink221/git_demo_.git
                host: Jinkyuui-MacBookPro.local
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/daniel/team_project/train.py
                python: CPython 3.9.6
                root: /Users/daniel/team_project
                startedAt: "2025-12-31T08:06:17.631275Z"
                writerId: 0c67cjn38jrcsdu6y4c5zx2v3yn5e58r
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
            "4": 3.9.6
            "5": 0.23.1
            "8":
                - 2
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 128
embed_size:
    value: 256
epochs:
    value: 50
hidden_size:
    value: 512
image_size:
    value:
        - 224
        - 224
learning_rate:
    value: 0.0003
nltk_data_dir:
    value: nltk_data
norm_mean:
    value:
        - 0.485
        - 0.456
        - 0.406
norm_std:
    value:
        - 0.229
        - 0.224
        - 0.225
num_layers:
    value: 1
num_workers:
    value: 4
optimizer_type:
    value: Adam
save_base_dir:
    value: ./checkpoints
shuffle:
    value: true
train_img_dir:
    value: ./data/images/train
train_json:
    value: ./data/captions/train.json
val_img_dir:
    value: ./data/images/val
val_json:
    value: ./data/captions/val.json
vocab_path:
    value: vocab.pkl
